uint8 ctrl_src_flag

float32 vx
float32 vy
float32 omega
float32 max_acc_x
float32 max_acc_y
float32 max_acc_omega
float32 pelvis_height
float32 pelvis_max_velocity

float32[8] left_joint_pos
float32[8] right_joint_pos
float32 head_yaw_pos
float32 head_pitch_pos

float32[8] left_joint_vel
float32[8] right_joint_vel
float32 head_yaw_vel
float32 head_pitch_vel

float32[8] left_joint_torque
float32[8] right_joint_torque
