float32 wheel_front_left_enc
float32 wheel_front_left_vel
float32 wheel_front_right_enc
float32 wheel_front_right_vel
float32 wheel_middle_enc
float32 wheel_middle_vel
float32 robot_heading
float32 robot_heading_vel
float32 pelvis_height
float32 pelvis_max_velocity

float32[8] left_joint_pos
float32[8] right_joint_pos
float32 head_yaw_pos
float32 head_pitch_pos

float32[8] left_joint_vel
float32[8] right_joint_vel

float32[8] left_joint_torque
float32[8] right_joint_torque
