# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_l_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_l_controller:
      type: position_controllers/GripperActionController


    arm_r_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_r_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_l_controller:
  ros__parameters:
    joints:
      - A_left_Degree1_joint
      - A_left_Degree2_joint
      - A_left_Degree3_joint
      - A_left_Degree4_joint
      - A_left_Degree5_joint
      - A_left_Degree6_joint
      - A_left_Degree7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_l_controller:
  ros__parameters:
    joint: A_left_Degree8_joint
arm_r_controller:
  ros__parameters:
    joints:
      - A_right_Degree1_joint
      - A_right_Degree2_joint
      - A_right_Degree3_joint
      - A_right_Degree4_joint
      - A_right_Degree5_joint
      - A_right_Degree6_joint
      - A_right_Degree7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_r_controller:
  ros__parameters:
    joint: A_right_Degree8_joint